networks:
  tracker-net:

services:
  database:
    image: postgres:17-alpine3.22
    container_name: tracker_database
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: tracker
      POSTGRES_SSL_MODE: disable
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - tracker-net
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      SWAGGER_JSON: /spec/openapi3.json
    ports:
      - "8081:8080"
    volumes:
      - ./backend/gen/http:/spec:ro # ← монтируем папку с openapi3.json :ro - read-only
volumes:
  postgres_data:
