# .github/workflows/golangci-lint.yml
name: golangci-lint

on:
  push:
    branches: ["**"] # Запускать на все ветки (можно ограничить, например: [ main, develop ])
  pull_request:
    branches: [main] # Опционально: также запускать при PR в main

jobs:
  golangci:
    name: Run golangci-lin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 2.7.2
          working-directory: backend
